#!/usr/bin/env python3
"""
Auto-annotate your custom images using YOLOv8 and save the result as a
COCO-format ground-truth JSON file.

Strategy
--------
Run YOLOv8n inference at a HIGH confidence threshold (default 0.50) on every
image in data/images/val/.  The resulting detections are saved as COCO-format
bounding-box annotations in data/annotations/instances_custom.json.

This "pseudo-labeling" approach creates a self-consistent dataset:
  • The annotation file correctly reflects what objects are detectable in each image.
  • mAP evaluated against these annotations measures backend / model consistency
    rather than absolute accuracy, which is acceptable for an assignment dataset.
  • Mention this in your report: "annotations generated by YOLOv8n at conf=0.5".

Usage
-----
    # from the backend/ directory (venv must be active):
    python ../scripts/create_custom_annotations.py

    # from project root:
    cd backend && python ../scripts/create_custom_annotations.py && cd ..

    # custom confidence or image dir:
    python ../scripts/create_custom_annotations.py --conf 0.45 --images-dir data/images/val

Output
------
    data/annotations/instances_custom.json   ← COCO-format GT annotations
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

# Allow running from project root or backend/
_here = Path(__file__).resolve()
_backend = _here.parents[1] / "backend"
if str(_backend) not in sys.path:
    sys.path.insert(0, str(_backend))

# COCO category list (standard 80-class COCO, 1-indexed)
COCO_CATEGORIES = [
    {"id": 1,  "name": "person",       "supercategory": "person"},
    {"id": 2,  "name": "bicycle",      "supercategory": "vehicle"},
    {"id": 3,  "name": "car",          "supercategory": "vehicle"},
    {"id": 4,  "name": "motorcycle",   "supercategory": "vehicle"},
    {"id": 5,  "name": "airplane",     "supercategory": "vehicle"},
    {"id": 6,  "name": "bus",          "supercategory": "vehicle"},
    {"id": 7,  "name": "train",        "supercategory": "vehicle"},
    {"id": 8,  "name": "truck",        "supercategory": "vehicle"},
    {"id": 9,  "name": "boat",         "supercategory": "vehicle"},
    {"id": 10, "name": "traffic light","supercategory": "outdoor"},
    {"id": 11, "name": "fire hydrant", "supercategory": "outdoor"},
    {"id": 13, "name": "stop sign",    "supercategory": "outdoor"},
    {"id": 14, "name": "parking meter","supercategory": "outdoor"},
    {"id": 15, "name": "bench",        "supercategory": "outdoor"},
    {"id": 16, "name": "bird",         "supercategory": "animal"},
    {"id": 17, "name": "cat",          "supercategory": "animal"},
    {"id": 18, "name": "dog",          "supercategory": "animal"},
    {"id": 19, "name": "horse",        "supercategory": "animal"},
    {"id": 20, "name": "sheep",        "supercategory": "animal"},
    {"id": 21, "name": "cow",          "supercategory": "animal"},
    {"id": 22, "name": "elephant",     "supercategory": "animal"},
    {"id": 23, "name": "bear",         "supercategory": "animal"},
    {"id": 24, "name": "zebra",        "supercategory": "animal"},
    {"id": 25, "name": "giraffe",      "supercategory": "animal"},
    {"id": 27, "name": "backpack",     "supercategory": "accessory"},
    {"id": 28, "name": "umbrella",     "supercategory": "accessory"},
    {"id": 31, "name": "handbag",      "supercategory": "accessory"},
    {"id": 32, "name": "tie",          "supercategory": "accessory"},
    {"id": 33, "name": "suitcase",     "supercategory": "accessory"},
    {"id": 34, "name": "frisbee",      "supercategory": "sports"},
    {"id": 35, "name": "skis",         "supercategory": "sports"},
    {"id": 36, "name": "snowboard",    "supercategory": "sports"},
    {"id": 37, "name": "sports ball",  "supercategory": "sports"},
    {"id": 38, "name": "kite",         "supercategory": "sports"},
    {"id": 39, "name": "baseball bat", "supercategory": "sports"},
    {"id": 40, "name": "baseball glove","supercategory": "sports"},
    {"id": 41, "name": "skateboard",   "supercategory": "sports"},
    {"id": 42, "name": "surfboard",    "supercategory": "sports"},
    {"id": 43, "name": "tennis racket","supercategory": "sports"},
    {"id": 44, "name": "bottle",       "supercategory": "kitchen"},
    {"id": 46, "name": "wine glass",   "supercategory": "kitchen"},
    {"id": 47, "name": "cup",          "supercategory": "kitchen"},
    {"id": 48, "name": "fork",         "supercategory": "kitchen"},
    {"id": 49, "name": "knife",        "supercategory": "kitchen"},
    {"id": 50, "name": "spoon",        "supercategory": "kitchen"},
    {"id": 51, "name": "bowl",         "supercategory": "kitchen"},
    {"id": 52, "name": "banana",       "supercategory": "food"},
    {"id": 53, "name": "apple",        "supercategory": "food"},
    {"id": 54, "name": "sandwich",     "supercategory": "food"},
    {"id": 55, "name": "orange",       "supercategory": "food"},
    {"id": 56, "name": "broccoli",     "supercategory": "food"},
    {"id": 57, "name": "carrot",       "supercategory": "food"},
    {"id": 58, "name": "hot dog",      "supercategory": "food"},
    {"id": 59, "name": "pizza",        "supercategory": "food"},
    {"id": 60, "name": "donut",        "supercategory": "food"},
    {"id": 61, "name": "cake",         "supercategory": "food"},
    {"id": 62, "name": "chair",        "supercategory": "furniture"},
    {"id": 63, "name": "couch",        "supercategory": "furniture"},
    {"id": 64, "name": "potted plant", "supercategory": "furniture"},
    {"id": 65, "name": "bed",          "supercategory": "furniture"},
    {"id": 67, "name": "dining table", "supercategory": "furniture"},
    {"id": 70, "name": "toilet",       "supercategory": "furniture"},
    {"id": 72, "name": "tv",           "supercategory": "electronic"},
    {"id": 73, "name": "laptop",       "supercategory": "electronic"},
    {"id": 74, "name": "mouse",        "supercategory": "electronic"},
    {"id": 75, "name": "remote",       "supercategory": "electronic"},
    {"id": 76, "name": "keyboard",     "supercategory": "electronic"},
    {"id": 77, "name": "cell phone",   "supercategory": "electronic"},
    {"id": 78, "name": "microwave",    "supercategory": "electronic"},
    {"id": 79, "name": "oven",         "supercategory": "electronic"},
    {"id": 80, "name": "toaster",      "supercategory": "electronic"},
    {"id": 81, "name": "sink",         "supercategory": "electronic"},
    {"id": 82, "name": "refrigerator", "supercategory": "electronic"},
    {"id": 84, "name": "book",         "supercategory": "indoor"},
    {"id": 85, "name": "clock",        "supercategory": "indoor"},
    {"id": 86, "name": "vase",         "supercategory": "indoor"},
    {"id": 87, "name": "scissors",     "supercategory": "indoor"},
    {"id": 88, "name": "teddy bear",   "supercategory": "indoor"},
    {"id": 89, "name": "hair drier",   "supercategory": "indoor"},
    {"id": 90, "name": "toothbrush",   "supercategory": "indoor"},
]

# 0-indexed class_id → official COCO category_id (non-contiguous)
COCO80_TO_COCO91 = [
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21,
    22, 23, 24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
    43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
    62, 63, 64, 65, 67, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 84,
    85, 86, 87, 88, 89, 90,
]


# ── CLI ────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Auto-annotate custom images using YOLOv8 (pseudo-labeling)",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--images-dir", default="../data/images/val",
                   help="Directory containing your images")
    p.add_argument("--output", default="../data/annotations/instances_custom.json",
                   help="Output COCO annotations JSON path")
    p.add_argument("--weights", default="yolov8n.pt",
                   help="YOLOv8 weights to use for annotation (auto-downloaded if not present)")
    p.add_argument("--conf", type=float, default=0.50,
                   help="Confidence threshold — higher = fewer but more reliable annotations")
    p.add_argument("--iou", type=float, default=0.45,
                   help="NMS IoU threshold")
    p.add_argument("--image-size", type=int, default=640,
                   help="Inference image size")
    p.add_argument("--min-anns", type=int, default=1,
                   help="Skip images with fewer detected objects than this")
    p.add_argument("--extensions", nargs="+",
                   default=["jpg", "jpeg", "png", "bmp", "webp"],
                   help="Image file extensions to process")
    return p.parse_args()


# ── Main ───────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()

    images_dir = Path(args.images_dir).resolve()
    output_path = Path(args.output).resolve()

    if not images_dir.exists():
        print(f"ERROR: images directory not found: {images_dir}")
        sys.exit(1)

    # Collect all image files (sorted for reproducibility)
    exts = {f".{e.lower().lstrip('.')}" for e in args.extensions}
    image_files = sorted(
        p for p in images_dir.iterdir()
        if p.is_file() and p.suffix.lower() in exts
    )

    if not image_files:
        print(f"ERROR: No image files found in {images_dir}")
        print(f"  Looking for extensions: {exts}")
        sys.exit(1)

    print("=" * 60)
    print("  Custom Dataset Auto-Annotation (YOLOv8 pseudo-labels)")
    print("=" * 60)
    print(f"  Images dir : {images_dir}  ({len(image_files)} files)")
    print(f"  Output     : {output_path}")
    print(f"  Confidence : {args.conf}  (IoU: {args.iou})")
    print(f"  Weights    : {args.weights}")
    print()

    # Load YOLOv8
    print("[1/3] Loading YOLOv8 model ...")
    try:
        from ultralytics import YOLO
    except ImportError:
        print("ERROR: ultralytics not installed. Run: pip install ultralytics")
        sys.exit(1)

    model = YOLO(args.weights)
    print(f"  Model loaded: {args.weights}\n")

    # Run inference on every image
    print(f"[2/3] Running inference on {len(image_files)} images ...")
    images_records = []
    annotations_records = []
    ann_id = 1
    skipped = 0

    t0 = time.perf_counter()
    for img_id, img_path in enumerate(image_files, start=1):
        # Run YOLOv8 inference
        results = model.predict(
            str(img_path),
            conf=args.conf,
            iou=args.iou,
            imgsz=args.image_size,
            verbose=False,
        )

        result = results[0]
        orig_h, orig_w = result.orig_shape[:2]

        # Build image record
        images_records.append({
            "id": img_id,
            "file_name": img_path.name,
            "width": orig_w,
            "height": orig_h,
        })

        # Build annotation records
        img_anns = 0
        if result.boxes is not None and len(result.boxes) > 0:
            for box in result.boxes:
                x1, y1, x2, y2 = box.xyxy[0].tolist()
                bw = x2 - x1
                bh = y2 - y1
                cls_id = int(box.cls[0])
                score = float(box.conf[0])
                coco_cat_id = (
                    COCO80_TO_COCO91[cls_id]
                    if 0 <= cls_id < len(COCO80_TO_COCO91)
                    else cls_id + 1
                )
                annotations_records.append({
                    "id": ann_id,
                    "image_id": img_id,
                    "category_id": coco_cat_id,
                    "bbox": [round(x1, 1), round(y1, 1),
                             round(bw, 1), round(bh, 1)],
                    "area": round(bw * bh, 1),
                    "iscrowd": 0,
                    "score": round(score, 4),   # extra field for reference
                })
                ann_id += 1
                img_anns += 1

        if img_anns < args.min_anns:
            skipped += 1

        if img_id % 20 == 0 or img_id == len(image_files):
            elapsed = time.perf_counter() - t0
            print(f"  {img_id:4d}/{len(image_files)}  "
                  f"({elapsed:.1f}s)  anns so far: {len(annotations_records)}")

    elapsed_total = time.perf_counter() - t0
    print(f"\n  Done in {elapsed_total:.1f}s")
    print(f"  Images with ≥{args.min_anns} detection(s): "
          f"{len(image_files) - skipped}/{len(image_files)}")
    print(f"  Total annotations: {len(annotations_records)}")

    # Filter: keep only images with >= min_anns detections
    if args.min_anns > 1:
        ann_count = {}
        for a in annotations_records:
            ann_count[a["image_id"]] = ann_count.get(a["image_id"], 0) + 1
        keep_ids = {img_id for img_id, cnt in ann_count.items() if cnt >= args.min_anns}
        images_records = [i for i in images_records if i["id"] in keep_ids]
        annotations_records = [a for a in annotations_records if a["image_id"] in keep_ids]
        print(f"  After min_anns filter: {len(images_records)} images, "
              f"{len(annotations_records)} annotations")

    # Write COCO JSON
    print(f"\n[3/3] Writing annotation file ...")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    coco_json = {
        "info": {
            "description": (
                f"Custom dataset — {len(images_records)} images auto-annotated "
                f"using YOLOv8n at conf={args.conf}"
            ),
            "version": "1.0",
            "year": 2026,
            "contributor": "auto-annotated",
        },
        "licenses": [],
        "images": images_records,
        "annotations": annotations_records,
        "categories": COCO_CATEGORIES,
    }

    with open(output_path, "w") as f:
        json.dump(coco_json, f, indent=2)

    print(f"  Written: {output_path}")
    print(f"  File size: {output_path.stat().st_size / 1024:.1f} KB")

    # Print category breakdown
    cat_map = {c["id"]: c["name"] for c in COCO_CATEGORIES}
    cat_counts: dict[str, int] = {}
    for a in annotations_records:
        name = cat_map.get(a["category_id"], str(a["category_id"]))
        cat_counts[name] = cat_counts.get(name, 0) + 1

    if cat_counts:
        print("\n  Top detected categories:")
        for name, cnt in sorted(cat_counts.items(), key=lambda x: -x[1])[:15]:
            bar = "█" * min(cnt, 40)
            print(f"    {name:<20} {cnt:>5}  {bar}")

    print()
    print("=" * 60)
    print("  Annotation file ready!")
    print("=" * 60)
    print(f"  Path    : {output_path}")
    print(f"  Images  : {len(images_records)}")
    print(f"  Ann.    : {len(annotations_records)}")
    print()
    print("  Use this file for evaluation:")
    print(f"    python scripts/evaluate_dataset.py \\")
    print(f"      --model yolov8 yolov5 --compare \\")
    print(f"      --annotations {output_path} \\")
    print(f"      --images-dir   {images_dir} \\")
    print(f"      --output       results/eval_report.csv")
    print()
    print("  NOTE: These are pseudo-labels generated by YOLOv8n.")
    print("  Disclose this in your report: mAP measures model consistency,")
    print("  not absolute ground-truth accuracy.")


if __name__ == "__main__":
    main()
