#!/usr/bin/env python3
"""
Validate a COCO-format annotation file for submission readiness.

Checks whether annotations are human-created (manual) or model-generated
(pseudo-labels). Prints a clear report and exits with a status code.

Exit codes
----------
  0  — manual annotations, valid for final mAP submission
  1  — pseudo-labels or template placeholder detected, NOT valid for final submission
  2  — file not found or invalid JSON

Usage
-----
    # Check if annotations are human-created:
    python scripts/validate_annotations.py \\
        --annotations data/annotations/instances_manual.json

    # Check the pseudo-label file (will warn but exit 0 with --allow-pseudo):
    python scripts/validate_annotations.py \\
        --annotations data/annotations/instances_custom.json --allow-pseudo
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


# ── Detection logic ────────────────────────────────────────────────────────

def _check(data: dict, key: str, fn) -> bool:
    try:
        return bool(fn(data))
    except Exception:
        return False


PSEUDO_CHECKS = [
    (
        'info.contributor is "auto-annotated"',
        lambda d: "auto-annotated" in d.get("info", {}).get("contributor", "").lower(),
    ),
    (
        "info.description indicates pseudo-labels",
        lambda d: any(
            kw in d.get("info", {}).get("description", "").lower()
            for kw in ("auto-annotated", "pseudo", "auto_annotated", "generated by yolo")
        ),
    ),
    (
        "Annotations contain a 'score' field (model confidence — pseudo-label marker)",
        lambda d: bool(d.get("annotations") and "score" in d["annotations"][0]),
    ),
]


def detect_annotation_type(data: dict) -> tuple[str, list[str]]:
    """
    Classify a loaded COCO annotation dict.

    Returns
    -------
    (annotation_type, reasons)
        annotation_type : "manual" | "pseudo" | "template"
        reasons         : human-readable list of triggered indicators
    """
    # Template / placeholder check
    if data.get("info", {}).get("status") == "NEEDS_ANNOTATIONS":
        return "template", [
            "File is a placeholder template — annotations array is empty. "
            "You must add human annotations before running final mAP evaluation."
        ]

    # Empty annotations array (even without the status flag)
    if not data.get("annotations"):
        return "template", [
            "Annotations array is empty — no bounding boxes found. "
            "Add human annotations first."
        ]

    triggered = [name for name, fn in PSEUDO_CHECKS if _check(data, name, fn)]
    ann_type = "pseudo" if triggered else "manual"
    return ann_type, triggered


def validate_file(path: str) -> tuple[str, list[str], dict]:
    """
    Load and validate a COCO annotation file.

    Returns
    -------
    (annotation_type, reasons, stats)
    """
    p = Path(path)
    if not p.exists():
        print(f"\nERROR: Annotation file not found: {p}")
        print("  Create it by running: python scripts/create_custom_annotations.py")
        print("  Or annotate manually. See docs/annotation_workflow.md\n")
        sys.exit(2)

    try:
        with open(p) as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        print(f"\nERROR: Invalid JSON in {p}: {e}\n")
        sys.exit(2)

    ann_type, reasons = detect_annotation_type(data)

    stats = {
        "num_images": len(data.get("images", [])),
        "num_annotations": len(data.get("annotations", [])),
        "num_categories": len(data.get("categories", [])),
        "contributor": data.get("info", {}).get("contributor", "(not set)"),
        "description": data.get("info", {}).get("description", "(not set)"),
    }

    return ann_type, reasons, stats


# ── CLI ────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Validate COCO annotations for final-submission readiness",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--annotations", required=True, metavar="JSON",
        help="Path to COCO-format annotations JSON file",
    )
    p.add_argument(
        "--allow-pseudo", action="store_true",
        help=(
            "Exit 0 even if pseudo-labels are detected. "
            "Use for sanity-check runs only — NOT for final submission."
        ),
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()
    ann_type, reasons, stats = validate_file(args.annotations)

    sep = "=" * 65
    print(f"\n{sep}")
    print("  Annotation File Validation Report")
    print(sep)
    print(f"  File         : {args.annotations}")
    print(f"  Images       : {stats['num_images']}")
    print(f"  Annotations  : {stats['num_annotations']}")
    print(f"  Categories   : {stats['num_categories']}")
    print(f"  Contributor  : {stats['contributor']}")
    print()

    # ── Template ──────────────────────────────────────────────────────────
    if ann_type == "template":
        print("  Status  : ⚠  PLACEHOLDER — annotations not yet added")
        print()
        for r in reasons:
            print(f"    • {r}")
        print()
        print("  Next steps:")
        print("    1. Annotate images with LabelImg, CVAT, or Roboflow.")
        print("    2. Export in COCO JSON format.")
        print("    3. Save as data/annotations/instances_manual.json")
        print("    4. Re-run this validator.")
        print()
        print("  See docs/annotation_workflow.md for step-by-step instructions.")
        print(sep + "\n")
        sys.exit(1)

    # ── Pseudo-labels ──────────────────────────────────────────────────────
    if ann_type == "pseudo":
        print("  Status  : ✗  PSEUDO-LABELS DETECTED")
        print()
        print("  Indicators found:")
        for r in reasons:
            print(f"    • {r}")
        print()
        print("  Problem:")
        print("    Pseudo-label annotations are generated by running YOLOv8n on the")
        print("    evaluation images. Evaluating YOLOv8/PyTorch against its own outputs")
        print("    produces mAP = 1.000 — a self-consistency score, not real accuracy.")
        print()
        print('  Assignment requirement: "Accuracy/mAP must be based on your own')
        print('  annotations." This means human-labelled ground truth, not model outputs.')
        print()
        print("  These pseudo-label results are useful as a sanity check (do the backends")
        print("  agree with each other?) but must NOT be reported as final accuracy.")
        print()
        print("  To fix:")
        print("    1. Annotate images manually. See docs/annotation_workflow.md")
        print("    2. Save annotations to data/annotations/instances_manual.json")
        print("    3. Run:  python scripts/evaluate_dataset.py --annotation-type manual \\")
        print("                 --annotations data/annotations/instances_manual.json ...")
        print(sep + "\n")
        if args.allow_pseudo:
            print("  --allow-pseudo flag set: exiting 0 anyway (sanity-check mode only).\n")
            sys.exit(0)
        sys.exit(1)

    # ── Manual ─────────────────────────────────────────────────────────────
    print("  Status  : ✓  MANUAL ANNOTATIONS — valid for final submission")
    print()
    print("  No pseudo-label indicators were detected. These annotations are")
    print("  human-created and suitable for reporting final mAP accuracy.")
    print()
    print("  Run evaluation:")
    print("    cd backend && python ../scripts/evaluate_dataset.py \\")
    print("        --model yolov8 yolov5 --compare \\")
    print("        --annotation-type manual \\")
    print("        --annotations ../data/annotations/instances_manual.json \\")
    print("        --images-dir ../data/images/val \\")
    print("        --output ../results/eval_report_manual.csv")
    print(sep + "\n")
    sys.exit(0)


if __name__ == "__main__":
    main()
