from __future__ import annotations

import os
from pathlib import Path
from typing import List
from pydantic_settings import BaseSettings
from functools import lru_cache


class Settings(BaseSettings):
    # Application
    APP_NAME: str = "Object Detection API"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False

    # Server
    HOST: str = "0.0.0.0"
    PORT: int = 8000

    # CORS — wildcard in dev; restrict to specific origins in production
    CORS_ORIGINS: List[str] = ["*"]

    # Directories (resolved relative to backend root)
    BASE_DIR: Path = Path(__file__).resolve().parents[2]
    UPLOAD_DIR: Path = BASE_DIR / "uploads"
    OUTPUT_DIR: Path = BASE_DIR / "outputs"
    WEIGHTS_DIR: Path = BASE_DIR / "weights"

    # Default model settings
    DEFAULT_CONFIDENCE: float = 0.25
    DEFAULT_IOU: float = 0.45
    DEFAULT_IMAGE_SIZE: int = 640

    # YOLOv8 weights (set to a custom path after training, or leave as model name
    # for Ultralytics auto-download, e.g. "yolov8n.pt")
    YOLOV8_WEIGHTS: str = "yolov8n.pt"

    # YOLOv5 weights (model variant string for torch.hub, e.g. "yolov5s")
    YOLOV5_WEIGHTS: str = "yolov5s"

    # Exported model paths (generated by scripts/export_*)
    YOLOV8_TORCHSCRIPT_PATH: str = "weights/yolov8n.torchscript"
    YOLOV8_ONNX_PATH: str = "weights/yolov8n.onnx"
    YOLOV5_TORCHSCRIPT_PATH: str = "weights/yolov5s.torchscript"
    YOLOV5_ONNX_PATH: str = "weights/yolov5s.onnx"

    # ONNX Runtime
    # Set to "CUDAExecutionProvider" to use GPU; auto-falls back to CPU if unavailable
    ONNX_EXECUTION_PROVIDER: str = "CPUExecutionProvider"

    # Benchmark defaults
    BENCHMARK_WARMUP_RUNS: int = 10
    BENCHMARK_NUM_RUNS: int = 100

    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"

    def ensure_directories(self) -> None:
        """Create upload/output/weights directories if they don't exist."""
        for d in [self.UPLOAD_DIR, self.OUTPUT_DIR, self.WEIGHTS_DIR]:
            d.mkdir(parents=True, exist_ok=True)


@lru_cache()
def get_settings() -> Settings:
    return Settings()
